#!/bin/sh
#
# kill-man: purges man pages and other docs
#
# (c) Kiëd Llaentenn <kiedtl@protonmail.com>
# See the LICENSE for copyright information.

[ -d "$1" ] || exit 1

for file in $(find ${1} -type f -name "*.1")
do
    echo "-> removing file '${file}'"
    rm -f "$file"
done

rm -rf "$1/share/man" "$1/share/doc"
