#!/bin/sh
#
# kill-man: purges man pages and other docs
#
# (c) Kiëd Llaentenn <kiedtl@protonmail.com>
# See the LICENSE for copyright information.

[ -d "$1" ] || exit 1

find ${1} -type f -name "*.1" -print0 | xargs -0 rm -f
rm -rf share/man share/doc
